export const doctors = [
  {
    id: "D1A9B4C2",
    name: "Dr. Richard James",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "4 years",
    about: "Dr. Richard James is a highly skilled General Physician with extensive experience in diagnosing and treating a wide range of medical conditions.",
    fees: 50,
    address: "123 Health Street, Lagos, Nigeria",
  },
  {
    id: "A2B8C7D4",
    name: "Dr. Jane Foster",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "General Physician",
    degree: "MBBS, MD",
    experience: "7 years",
    about: "Dr. Jane Foster specializes in women's health, providing top-notch gynecological care and prenatal services.",
    fees: 60,
    address: "45 Blossom Avenue, Abuja, Nigeria",
  },
  {
    id: "B3C6D5A9",
    name: "Dr. Michael Peters",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "General Physician",
    degree: "MBBS, MD",
    experience: "6 years",
    about: "Dr. Michael Peters is known for his expertise in skin treatments and cosmetic dermatology.",
    fees: 70,
    address: "78 Skin Care Lane, Ikeja, Lagos",
  },
  {
    id: "C4D5A3B7",
    name: "Dr. Susan Adams",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Gynecologist",
    degree: "MBBS, MD",
    experience: "5 years",
    about: "Dr. Susan Adams provides exceptional medical care for infants, children, and adolescents.",
    fees: 55,
    address: "98 Child Street, Lekki, Lagos",
  },
  {
    id: "D5A2B1C8",
    name: "Dr. Mark Williams",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Gynecologist",
    degree: "MBBS, DM",
    experience: "10 years",
    about: "Dr. Mark Williams specializes in treating neurological disorders with a focus on personalized patient care.",
    fees: 100,
    address: "12 Brain Health Blvd, Victoria Island, Lagos",
  },
  {
    id: "E1B2C4D6",
    name: "Dr. Emily Thomas",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Dermatologist",
    degree: "MBBS, MD",
    experience: "8 years",
    about: "Dr. Emily Thomas provides expert care for digestive system disorders and related issues.",
    fees: 80,
    address: "34 Digestive Drive, Abuja, Nigeria",
  },
  {
    id: "F2C3D5A1",
    name: "Dr. Henry Brown",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Dermatologist",
    degree: "MBBS, MS",
    experience: "12 years",
    about: "Dr. Henry Brown is a top orthopedic surgeon, specializing in joint replacement and fracture management.",
    fees: 150,
    address: "56 Bone Care Street, Ikeja, Lagos",
  },
  {
    id: "G3D1A2B4",
    name: "Dr. Olivia Green",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Cardiologist",
    degree: "MBBS, DM",
    experience: "15 years",
    about: "Dr. Olivia Green is an expert cardiologist offering comprehensive heart care services.",
    fees: 200,
    address: "78 Heart Avenue, Lekki, Lagos",
  },
  {
    id: "H4B3A2D5",
    name: "Dr. Andrew Scott",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Cardiologist",
    degree: "MBBS, DM",
    experience: "9 years",
    about: "Dr. Andrew Scott offers specialized care in hormone-related conditions, including diabetes and thyroid issues.",
    fees: 90,
    address: "67 Endocrine Street, Victoria Island, Lagos",
  },
  {
    id: "I5A1C3B7",
    name: "Dr. Sarah Johnson",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Pediatrician",
    degree: "MBBS, MD",
    experience: "10 years",
    about: "Dr. Sarah Johnson is a compassionate psychiatrist dedicated to mental health treatment and therapy.",
    fees: 120,
    address: "89 Mental Health Road, Abuja, Nigeria",
  },
  {
    id: "J1B2C3D4",
    name: "Dr. Patrick Lee",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Pediatrician",
    degree: "MBBS, DM",
    experience: "14 years",
    about: "Dr. Patrick Lee provides expert cancer care with advanced treatment options.",
    fees: 250,
    address: "23 Cancer Care Lane, Lekki, Lagos",
  },
  {
    id: "K2C1A4D6",
    name: "Dr. Charlotte Wilson",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Neurologist",
    degree: "MBBS, MCh",
    experience: "11 years",
    about: "Dr. Charlotte Wilson offers specialized care in urological conditions and surgeries.",
    fees: 130,
    address: "45 Kidney Lane, Ikeja, Lagos",
  },
  {
    id: "L3A1B2C5",
    name: "Dr. Daniel Morgan",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Neurologist",
    degree: "MBBS, MS",
    experience: "13 years",
    about: "Dr. Daniel Morgan is an experienced ophthalmologist providing expert eye care and vision correction services.",
    fees: 140,
    address: "101 Vision Avenue, Lekki, Lagos",
  },
  {
    id: "M4B2D1C3",
    name: "Dr. Amanda Evans",
    image: "https://res.cloudinary.com/daarrcw3q/image/upload/v1743082204/file_3_1_qnh91v.png",
    speciality: "Neurologist",
    degree: "MBBS, MD",
    experience: "8 years",
    about: "Dr. Amanda Evans provides expert care in respiratory disorders and lung conditions.",
    fees: 110,
    address: "56 Respiratory Lane, Abuja, Nigeria",
  },
];
